let body = document.getElementById("body");
let div = document.createElement("div");
body.appendChild(div);
let p0 = document.createElement("p");
let text0 = document.createTextNode("Hello there,");
p0.appendChild(text0);
let p1 = document.createElement("p");
let text1 = document.createTextNode("I am a llama, hear my sirens roar:");
p1.appendChild(text1);
div.appendChild(p0);
div.appendChild(p1);
let ul = document.createElement("ul");
div.appendChild(ul);
let li0 = document.createElement("li");
let the = document.createTextNode("The");
li0.appendChild(the);
let li1 = document.createElement("li");
let duck = document.createTextNode("Duck");
li1.appendChild(duck);
let li2 = document.createElement("li");
let lemonade = document.createTextNode("Lemonade");
li2.appendChild(lemonade);
let li3 = document.createElement("li");
let stand = document.createTextNode("Stand");
li3.appendChild(stand);
ul.appendChild(li0);
ul.appendChild(li1);
ul.appendChild(li2);
ul.appendChild(li3);