let body = document.getElementById("body");
let div = document.createElement("div");
div.style.backgroundColor = "#cccccc";
body.appendChild(div);
let a = document.createElement("a");
a.target = "_blank";
a.href = "https://google.com";
let img = document.createElement("img");
img.src = "https://i.ytimg.com/vi/yJiVZUKAS84/maxresdefault.jpg";
img.alt = "Me and my sibling";
a.appendChild(img);
div.appendChild(a);
let hr = document.createElement("hr");
div.appendChild(hr);
let table = document.createElement("table");
div.appendChild(table);
let tr0 = document.createElement("tr");
let th0 = document.createElement("th");
let name = document.createTextNode("Name");
let th1 = document.createElement("th");
let age = document.createTextNode("Age");
let th2 = document.createElement("th");
let height = document.createTextNode("Height");
th0.appendChild(name);
th1.appendChild(age);
th2.appendChild(height);
tr0.appendChild(th0);
tr0.appendChild(th1);
tr0.appendChild(th2);
table.appendChild(tr0);
let tr1 = document.createElement("tr");
let td1 = document.createElement("td");
let sarah = document.createTextNode("Sarah");
let td2 = document.createElement("td");
let twotwo = document.createTextNode("22");
let td3 = document.createElement("td");
let one88 = document.createTextNode("188");
td1.appendChild(sarah);
td2.appendChild(twotwo);
td3.appendChild(one88);
tr1.appendChild(td1);
tr1.appendChild(td2);
tr1.appendChild(td3);
table.appendChild(tr1);
let tr2 = document.createElement("tr");
let td4 = document.createElement("td");
let lin = document.createTextNode("Lin");
let td5 = document.createElement("td");
let fourtwo = document.createTextNode("42");
let td6 = document.createElement("td");
let one34 = document.createTextNode("134");
td4.appendChild(lin);
td5.appendChild(fourtwo);
td6.appendChild(one34);
tr2.appendChild(td4);
tr2.appendChild(td5);
tr2.appendChild(td6);
table.appendChild(tr2);
let tr3 = document.createElement("tr");
let td7 = document.createElement("td");
let samir = document.createTextNode("Samir");
let td8 = document.createElement("td");
let twoone = document.createTextNode("21");
let td9 = document.createElement("td");
let one55 = document.createTextNode("155");
td7.appendChild(samir);
td8.appendChild(twoone);
td9.appendChild(one55);
tr3.appendChild(td7);
tr3.appendChild(td8);
tr3.appendChild(td9);
table.appendChild(tr3);
let tr4 = document.createElement("tr");
let td10 = document.createElement("td");
let wayne = document.createTextNode("Wayne");
let td11 = document.createElement("td");
let twonine = document.createTextNode("29");
let td12 = document.createElement("td");
let one62 = document.createTextNode("162");
td10.appendChild(wayne);
td11.appendChild(twonine);
td12.appendChild(one62);
tr4.appendChild(td10);
tr4.appendChild(td11);
tr4.appendChild(td12);
table.appendChild(tr4);
let tr5 = document.createElement("tr");
let td13 = document.createElement("td");
let eckhart = document.createTextNode("Eckhart");
let td14 = document.createElement("td");
let oneonetwo = document.createTextNode("112");
let td15 = document.createElement("td");
let one44 = document.createTextNode("144");
td13.appendChild(eckhart);
td14.appendChild(oneonetwo);
td15.appendChild(one44);
tr5.appendChild(td13);
tr5.appendChild(td14);
tr5.appendChild(td15);
table.appendChild(tr5);
